# Generated by Django 2.1 on 2018-10-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180426_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumb',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
