# Generated by Django 2.1 on 2018-11-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181014_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='blogtype',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
    ]
